#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#include <iostream>

enum errors {
    FAILED_SET_MOTOR_CMD,
    FAILED_CONNECTION,
    FAILED_READ_ENCODER_COUNT,
    FAILED_READ_ENCODER_SPEED,
    WRONG_SIZE_JOINTSTATE_CMD,
    WORNG_INDEXING,
    PREFIX_INVALID,
    POSITION_MESSAGE_ID_ERROR,
    CANNOT_OPEN_PORT,
    DEVICE_NOT_CONNECTED,
    TRANSMISSION_FAILED,
    NO_SERIAL_RECEIVE,
    SERIAL_IO,
    EMPTY_STRING
};

void printErrorCode(errors code);
#endif